---

- name: This is a hello-world example
  hosts: ansibleclient01.local
  tasks:
  - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
    copy: content="hello world\n" dest=/tmp/testfile.txt
    
  - name: Load json vars
    include_vars:
      dir: 'vars'
      extensions:
        - json

  - name: Also load json vars
    include_vars:
      file: vars/example_config.json
      name: auth_config

  - debug:
      msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

  - shell: /usr/bin/uptime
    register: result

  - debug:
      var: result
      verbosity: 2