---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        users:
          alice: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZ36QoIhiCE21EIidBkQX3MKqMP2n0XOK3CfXzguJcqW6wjAVi55I3h/cQjbSvSnfljr0kq/Ut/5kGMw3suO88yPwNe16l4ga8wfyZyhURNtJYUhRcvMWLnIN5Q+WvrDltxKICozvYz71gGkmBnM/j5qAhUYEnU42NXDCoCw3++fMj/8fU2tvUOaybe3lxTGsTikNREn3aIdXuIt2BCck9GFycbWvdGFS9fUaTkj57waXu9DMSqETbuKdaPyGdEEbgbP7+dQnaSi2C9FJd1OPasVU3FJCiP3AWblhJWpf0TZO86uCUfD3Y/6JsGilJIw2i1PQ+rjA3P2NdW+jUV8MZ"
        servers:
          instance:
            - "alice"
  lint:
    name: ansible-lint
scenario:
  name: test-basic-runs
verifier:
  name: testinfra
  lint:
    name: flake8
